/**
 * Fetch and self-host exactly the font subsets this page needs.
 *
 * Why self-host: the page is opened cold from a WhatsApp message, usually on
 * mobile data. A third-party stylesheet costs a DNS lookup, a TLS handshake
 * and a round trip before any text can be shaped — and if it fails, the
 * Devanagari constellation has no glyphs to sample. Local, pre-subsetted
 * woff2 files remove all of that.
 *
 * The Latin faces are subset to printable ASCII plus the punctuation the copy
 * uses. The Devanagari and Telugu faces are subset to their one phrase each,
 * so re-run this script if you change either phrase.
 *
 *   node tools/fetch-fonts.mjs
 *
 * All four families are © their authors under the SIL Open Font License 1.1.
 */
import { writeFile, mkdir, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';
const OUT_DIR = 'public/fonts';
const CSS_PATH = 'public/fonts.css';

const LATIN =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789' +
  ' .,:;!?\'"()[]{}-–—…/&+%#@*·’‘“”°';
const DEVANAGARI = 'शुभ दीपावली';
/* every Telugu string the page renders, so the subset carries their glyphs */
const TELUGU = [
  'శుభ దీపావళి',
  'ఈ దీపావళి మీరు నడిచే ప్రతి దారికి వెలుగును, ప్రతి ఇంటికి వెచ్చదనాన్ని, ప్రతి కొత్త ఆరంభానికి ఆశను తీసుకురావాలి.',
  'మీకు, మీ కుటుంబ సభ్యులకు ఆనందం, ఆరోగ్యం, శాంతి, సౌభాగ్యం కలగాలని మనస్ఫూర్తిగా కోరుకుంటున్నాను.',
  'మీ దీపావళి సురక్షితంగా, ఆనందంగా, అందంగా సాగాలి.',
  'హృదయపూర్వక దీపావళి శుభాకాంక్షలు',
].join(' ');

const FAMILIES = [
  { id: 'cormorant', spec: 'Cormorant+Garamond:wght@300;500;600', text: LATIN },
  { id: 'inter', spec: 'Inter:wght@400;500', text: LATIN },
  { id: 'notoserifdeva', spec: 'Noto+Serif+Devanagari:wght@700', text: DEVANAGARI },
  { id: 'notosanstelugu', spec: 'Noto+Sans+Telugu:wght@500', text: TELUGU },
];

const get = async (url, asBuffer = false) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
};

/* start clean so a narrowed subset never leaves a stale, larger file behind */
await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

let out = [
  '/* Self-hosted font subsets — generated by tools/fetch-fonts.mjs.',
  '   Cormorant Garamond, Inter, Noto Serif Devanagari, Noto Sans Telugu,',
  '   © their respective authors, SIL Open Font License 1.1.',
  '   Re-run the generator rather than editing this file. */',
  '',
].join('\n');

let total = 0;
const seen = new Map();   // remote url -> local filename

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.spec}` +
    `&display=swap&text=${encodeURIComponent(fam.text)}`;
  const css = await get(url);
  const blocks = css.match(/@font-face\s*\{[^}]*\}/gs) || [];
  if (!blocks.length) throw new Error(`no @font-face returned for ${fam.spec}`);

  let n = 0;
  for (const block of blocks) {
    const src = block.match(/url\((https:\/\/[^)]+)\)/);
    if (!src) continue;
    const weight = (block.match(/font-weight:\s*([\d ]+)/) || [, '400'])[1].trim();
    const style = (block.match(/font-style:\s*(\w+)/) || [, 'normal'])[1];
    const family = (block.match(/font-family:\s*'([^']+)'/) || [, fam.id])[1];
    const range = (block.match(/unicode-range:\s*([^;}]+)/) || [])[1];

    const name = `${fam.id}-${weight.replace(/\s+/g, '_')}${style === 'italic' ? 'i' : ''}.woff2`;

    /* several weights of a variable family share one file — fetch it once */
    if (!seen.has(src[1])) {
      const bytes = await get(src[1], true);
      await writeFile(join(OUT_DIR, name), bytes);
      seen.set(src[1], name);
      total += bytes.length;
    }
    const file = seen.get(src[1]);
    n++;

    out += `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      (range ? `  unicode-range: ${range.trim()};\n` : '') +
      `}\n\n`;
  }
  console.log(`  ${fam.spec.padEnd(38)} ${n} face(s)`);
}

await writeFile(CSS_PATH, out);
console.log(`\nwrote ${CSS_PATH} (${(await readFile(CSS_PATH)).length} B)`);
console.log(`font payload: ${(total / 1024).toFixed(1)} KB across ${FAMILIES.length} families`);
